from PyQt5 import QtCore, QtWidgets, QtGui

from src.specialWidgets import CanvasWidget, ToolButton, LineEdit, Slider
from src.defaults import *

class Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 619)
        MainWindow.setMinimumSize(QtCore.QSize(809, 619))
        MainWindow.setMaximumSize(QtCore.QSize(809, 619))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.statsCanvas = CanvasWidget(self.centralwidget)
        self.statsCanvas.setGeometry(QtCore.QRect(0, 460, 631, 131))
        self.statsCanvas.setObjectName("statsCanvas")
        self.mainCanvas = CanvasWidget(self.centralwidget)
        self.mainCanvas.setGeometry(QtCore.QRect(0, 0, 631, 460))
        self.mainCanvas.setObjectName("mainCanvas")
        self.pauseButton = ToolButton(self.centralwidget, "||", "|>")
        self.pauseButton.setGeometry(QtCore.QRect(710, 570, 27, 26))
        self.pauseButton.setObjectName("pauseButton")
        self.timeLowerButton = ToolButton(self.centralwidget, "<<")
        self.timeLowerButton.setGeometry(QtCore.QRect(680, 570, 27, 26))
        self.timeLowerButton.setObjectName("timeLowerButton")
        self.timeHigherButton = ToolButton(self.centralwidget, ">>")
        self.timeHigherButton.setGeometry(QtCore.QRect(740, 570, 27, 26))
        self.timeHigherButton.setObjectName("timeHigherButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(640, 60, 160, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.massLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.massLabel.setObjectName("massLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.massLabel)
        self.velocityLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.velocityLabel.setObjectName("velocityLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.velocityLabel)
        self.heightLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.radiusLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.radiusLabel.setObjectName("radiusLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radiusLabel)
        self.massValue = LineEdit(self.formLayoutWidget, MASS)
        self.massValue.setObjectName("massValue")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.massValue)
        self.velocityValue = LineEdit(self.formLayoutWidget, VELOCITY)
        self.velocityValue.setObjectName("velocityValue")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.velocityValue)
        self.heightValue = LineEdit(self.formLayoutWidget, HEIGHT)
        self.heightValue.setObjectName("heightValue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.heightValue)
        self.radiusValue = LineEdit(self.formLayoutWidget, RADIUS)
        self.radiusValue.setObjectName("radiusValue")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radiusValue)
        self.kLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kLabel.setObjectName("kLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.kLabel)
        self.kValue = LineEdit(self.formLayoutWidget, K)
        self.kValue.setObjectName("kValue")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.kValue)
        self.settingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.settingsLabel.setGeometry(QtCore.QRect(640, 8, 161, 41))
        self.qualityLabel = QtWidgets.QLabel(self.centralwidget)
        self.qualityLabel.setGeometry(QtCore.QRect(650, 230, 141, 20))
        self.qualityLabel.setObjectName("qualityLabel")
        self.qualityValue = Slider(self.centralwidget, 200, 5000)
        self.qualityValue.setGeometry(QtCore.QRect(640, 250, 160, 16))
        self.qualityValue.setOrientation(QtCore.Qt.Horizontal)
        self.qualityValue.setObjectName("qualityValue")
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setObjectName("settingsLabel")
        self.restartButton = ToolButton(self.centralwidget, "Restart")
        self.restartButton.setGeometry(QtCore.QRect(680, 530, 87, 26))
        self.restartButton.setObjectName("restartButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.massLabel.setText(_translate("MainWindow", "Mass"))
        self.velocityLabel.setText(_translate("MainWindow", "Velocity"))
        self.heightLabel.setText(_translate("MainWindow", "Height"))
        self.radiusLabel.setText(_translate("MainWindow", "Radius"))
        self.kLabel.setText(_translate("MainWindow", "K"))
        self.qualityLabel.setText(_translate("MainWindow", "Performance/Quality"))
        self.settingsLabel.setText(_translate("MainWindow", "     Settings"))
